### ISSUE TITLE
Wrong statistics on currently live version

### ISSUE THREAD

**Issue by Black-Platypus** [AhoyLemon/damn.dog#15]
Hi,
Nice game, but it seems there is something wrong with the statistics:
After about 200 questions it said "game over" and gave me the statistics: Rounds played: 12 - Correct: 129 - Incorrect: 7 - Percent: 68%﻿

Am I misinterpreting something? Then it's just a communications problem ^^

**Comment by AhoyLemon** [comment]
Hm, okay I'll look at how the math works. Did you actually manage to get to Game Over with only 7 wrong answers?

**Comment by Black-Platypus** [comment]
Hi,

 

no, 68% correct seems about right

The "rounds" and "incorrect" counters just seem terribly off :)

 

Played on Firefox, if that's of any help.

I didn't think to have the console open while I played, all I have are the final stats
 

Mit freundlichen Grüßen

Benjamin Philipp

 
 

Gesendet: Donnerstag, 03. November 2016 um 15:47 Uhr
Von: Lemon notifications@github.com
An: AhoyLemon/Damn-Dog Damn-Dog@noreply.github.com
Cc: svArtist benjamin_philipp@gmx.de, Author author@noreply.github.com
Betreff: Re: [AhoyLemon/Damn-Dog] Wrong statistics on currently live version (#15)

Hm, okay I'll look at how the math works. Did you actually manage to get to Game Over with only 7 wrong answers?

**Comment by AhoyLemon** [comment]
I think I have an idea on what happened, I'll look into it when I have a bit of time.

**Comment by Black-Platypus** [comment]
Nice :)

Don't feel obligated to rush yourself for me (wait, is that even English? Sounds weird right now O.o), just dropped by to inform you of my findings

(Just in case you felt you needed to tell me you'll look into it to appease me or something^^)
 

Mit freundlichen Grüßen

Benjamin Philipp

 
 

Gesendet: Donnerstag, 03. November 2016 um 17:24 Uhr
Von: Lemon notifications@github.com
An: AhoyLemon/Damn-Dog Damn-Dog@noreply.github.com
Cc: svArtist benjamin_philipp@gmx.de, Author author@noreply.github.com
Betreff: Re: [AhoyLemon/Damn-Dog] Wrong statistics on currently live version (#15)

I think I have an idea on what happened, I'll look into it when I have a bit of time.
