### ISSUE TITLE
#184 and #180 are outdated

### ISSUE THREAD

**Issue by thislooksfun** [AhoyLemon/damn.dog#20]
[184](http://damn.dog/#184) ([How To Be Comfortable in Your Own Skin](http://www.wikihow.com/Be-Comfortable-in-Your-Own-Skin)) and [180](http://damn.dog/#180) ([How To Feed a Snake](http://www.wikihow.com/Feed-a-Snake)) are using images that no longer occur within the actual articles.

**Comment by AhoyLemon** [comment]
wikiHow is an everchanging website, and that's always gonna be a thing that happens.  I can't keep up with that process, and as such wouldn't be interested in yanking an image unless there was an image to replace it with.

**Comment by thislooksfun** [comment]
Fair enough. Just thought I'd mention it.

**Comment by AhoyLemon** [comment]
It's a fair point. Maybe I should try to figure out somewhere to put "These images were accurate as of the time they were posted" language.

**Comment by ghost** [comment]
How about `At the time of deployment, these images were displayed on the
relevant articles`?

**Comment by thislooksfun** [comment]
The main reason I mentioned it is because I like to look at what the step is for particularly... odd images. Maybe attach the name of the step in the future?
