### ISSUE TITLE
Add docs showing how to add more pics

### ISSUE THREAD

**Issue by jgonera** [AhoyLemon/damn.dog#4]
After looking at the repo for a couple of minutes, it's still not obvious where to add answers for a picture.

**Comment by AhoyLemon** [comment]
Alright.

I've never tried to do anything with that GitHub wiki feature, maybe this is a good opportunity.

**Comment by jgonera** [comment]
Or just add it in the readme.

**Comment by AhoyLemon** [comment]
Lemmie know if [this](https://github.com/AhoyLemon/Damn-Dog/wiki/How-To-Add-New-Images-To-Damn.Dog) explains it.
