### ISSUE TITLE
Safari Select Truncation (iOS)

### ISSUE THREAD

**Issue by AhoyLemon** [AhoyLemon/damn.dog#9]
I've only recently been made aware that there's a display issue on iPhones. Because Safari will truncate the select options, you get readouts like `How To Resist Sexual Desires By Following...`, which is usability that could be better.

If anyone wants to suggest something better, I'd love to hear it.

**Comment by mike** [comment]
Does adding an empty `<optgroup>` work?

http://stackoverflow.com/questions/19398154/how-to-fix-truncated-text-on-select-element-on-ios7/19734474#19734474

**Comment by AhoyLemon** [comment]
Hmmm, that's an interesting idea.

I don't have a iPhone available right now, @mike do you wanna try to test that idea in your fork?

**Comment by AhoyLemon** [comment]
Hey @mike , it worked.
